### ISSUE TITLE
route not found on fresh foreman 3.3.0-1

### ISSUE THREAD

**Issue by madelaney** [theforeman/puppet-puppetserver_foreman#23]
I have a new installation of `foreman` (package version v3.3.0-1) on Ubuntu 20.04 LTS, using `puppet-puppetserver_foreman` (module version v2.1.0).

When puppet, or me (manually), tries to run we get a "no route" found in the foreman logs.

The output on the console looks like:
```
root@foreman001:~/puppet# /etc/puppetlabs/puppet/node.rb  foreman001.company-domain.com
/etc/puppetlabs/puppet/node.rb:446: warning: constant ::TimeoutError is deprecated
Error retrieving node foreman001.company-domain.com: Net::HTTPNotFound
Check Foreman's /var/log/foreman/production.log for more information.
```

From `production.log` the stack trace looks like:
```
2022-09-13T10:02:33 [F|app|836e1956]   
 836e1956 | ActionController::RoutingError (No route matches [GET] "/node/foreman001.company-domain.com"):
 836e1956 |   
 836e1956 | lib/foreman/middleware/logging_context_request.rb:11:in `call'
2022-09-13T10:06:23 [I|app|8a448d7f] Started GET "/node/foreman001.company-domain.com?format=yml" for 20.246.22.104 at 2022-09-13 10:06:23 -0400
2022-09-13T10:06:23 [F|app|8a448d7f]   
 8a448d7f | ActionController::RoutingError (No route matches [GET] "/node/foreman001.company-domain.com"):
 8a448d7f |   
 8a448d7f | lib/foreman/middleware/logging_context_request.rb:11:in `call'
```

**Comment by madelaney** [comment]
Turns out we didn't have the `foreman-puppet` module installed. 🤦
